### ISSUE TITLE
A couple errors 

### ISSUE THREAD

**Issue by rahulxdd** [jsphwllng/internet_monitor#1]
Traceback (most recent call last):
  File "application.py", line 37, in <module>
    record(length, download, upload)
  File "F:\Python\speedtest\internet_monitor-master\monitor.py", line 32, in record
    make_graph(str(start_day)[:10], download, upload)
  File "F:\Python\speedtest\internet_monitor-master\graph_maker.py", line 15, in make_graph
    x.append(str(row[0]))
IndexError: list index out of range

**Comment by jsphwllng** [comment]
all appears to be working on my end - can you provide what you did prior to this error, please?

**Comment by rahulxdd** [comment]
I just downloaded the repo on my laptop and ran the application.py file. Did it again just now and got the same error.

`
now generating graph...
Traceback (most recent call last):
  File "application.py", line 37, in <module>
    record(length, download, upload)
  File "F:\Python\speedtest\internet_monitor-master\monitor.py", line 32, in record
    make_graph(str(start_day)[:10], download, upload)
  File "F:\Python\speedtest\internet_monitor-master\graph_maker.py", line 15, in make_graph
    x.append(str(row[0]))
IndexError: list index out of range
`

**Comment by jsphwllng** [comment]
can you run pip3 list and show me the results please

**Comment by rahulxdd** [comment]
`

F:\Python\speedtest\internet_monitor-master>pip3 list
Package                  Version
------------------------ ---------
apipkg                   1.5
appdirs                  1.4.4
asgiref                  3.2.10
atomicwrites             1.4.0
attrs                    19.3.0
cachetools               4.1.1
certifi                  2020.6.20
chardet                  3.0.4
colorama                 0.4.3
cycler                   0.10.0
DateTime                 4.3
distlib                  0.3.1
execnet                  1.7.1
filelock                 3.0.12
google-api-core          1.22.4
google-api-python-client 1.12.3
google-auth              1.22.1
google-auth-httplib2     0.0.4
google-auth-oauthlib     0.4.1
googleapis-common-protos 1.52.0
httplib2                 0.18.1
idna                     2.10
importlib-metadata       1.6.0
kiwisolver               1.2.0
matplotlib               3.3.2
more-itertools           8.3.0
MouseInfo                0.1.3
numpy                    1.19.2
oauth2client             4.1.3
oauthlib                 3.1.0
packaging                20.4
pbr                      5.4.5
Pillow                   8.0.0
pip                      20.2.3
pluggy                   0.13.1
protobuf                 3.13.0
py                       1.8.1
pyasn1                   0.4.8
pyasn1-modules           0.2.8
PyAutoGUI                0.9.52
PyDrive                  1.3.1
PyGetWindow              0.0.9
PyMsgBox                 1.0.9
pyparsing                2.4.7
pyperclip                1.8.1
PyRect                   0.1.4
PyScreeze                0.1.26
pytest                   5.4.2
pytest-cache             1.0
python-dateutil          2.8.1
PyTweening               1.0.3
pytz                     2020.1
PyYAML                   5.3.1
requests                 2.24.0
requests-oauthlib        1.3.0
rsa                      4.6
setuptools               40.8.0
six                      1.15.0
speedtest-cli            2.1.2
sqlparse                 0.3.1
stevedore                3.0.0
uritemplate              3.0.1
urllib3                  1.25.10
virtualenv               20.0.26
virtualenv-clone         0.5.4
virtualenvwrapper        4.8.4
virtualenvwrapper-win    1.2.6
wcwidth                  0.1.9
words                    0.0.1
zipp                     3.1.0
zope.interface           5.1.2
WARNING: You are using pip version 20.2.3; however, version 20.2.4 is available.
You should consider upgrading via the 'c:\users\rahul\appdata\local\programs\python\python37-32\python.exe -m pip install --upgrade pip' command.`

**Comment by jsphwllng** [comment]
I can recreate the index out of range error if i give `0` as an argument for the minutes. How long are you telling the program to run for?

**Comment by rahulxdd** [comment]
I ran twice for 5 minutes and then once for 2 minutes. I couldn't understand what's the issue.

**Comment by jsphwllng** [comment]
can you show me the entire console log for a 1 minute run

**Comment by rahulxdd** [comment]
Microsoft Windows [Version 10.0.19041.572]
(c) 2020 Microsoft Corporation. All rights reserved.

F:\Python\speedtest\internet_monitor-master>python application.py



 _       _                       _                           _ _
(_)_ __ | |_ ___ _ __ _ __   ___| |_   _ __ ___   ___  _ __ (_) |_ ___  _ __
| | '_ \| __/ _ \ '__| '_ \ / _ \ __| | '_ ` _ \ / _ \| '_ \| | __/ _ \| '__|
| | | | | ||  __/ |  | | | |  __/ |_  | | | | | | (_) | | | | | || (_) | |
|_|_| |_|\__\___|_|  |_| |_|\___|\__| |_| |_| |_|\___/|_| |_|_|\__\___/|_|




how many minutes should we monitor your internet for?
> 2
what is your expected download speed in Mb/s?
> 120
what is your expected upload speed in Mb/s?
> 120
if you have imported your google drive API key you will now be asked to log into your google drive account

now monitoring your internet speed...
it is now 2020-10-26 9:36:53.275694 and i will stop recording at 2020-10-26 9:38:53.275694
time: 13:36:53, downspeed: 115.35 Mb/s, upspeed: 119.01 Mb/s
time: 13:37:14, downspeed: 112.7 Mb/s, upspeed: 119.06 Mb/s
time: 13:37:35, downspeed: 116.45 Mb/s, upspeed: 119.06 Mb/s
time: 13:37:56, downspeed: 112.65 Mb/s, upspeed: 119.18 Mb/s
time: 13:38:16, downspeed: 110.85 Mb/s, upspeed: 118.84 Mb/s
time: 13:38:37, downspeed: 114.67 Mb/s, upspeed: 119.14 Mb/s

now generating graph...
Traceback (most recent call last):
  File "application.py", line 37, in <module>
    record(length, download, upload)
  File "F:\Python\speedtest\internet_monitor-master\monitor.py", line 32, in record
    make_graph(str(start_day)[:10], download, upload)
  File "F:\Python\speedtest\internet_monitor-master\graph_maker.py", line 15, in make_graph
    x.append(str(row[0]))
IndexError: list index out of range

F:\Python\speedtest\internet_monitor-master>pip3 list
Package                  Version
------------------------ ---------
apipkg                   1.5
appdirs                  1.4.4
asgiref                  3.2.10
atomicwrites             1.4.0
attrs                    19.3.0
cachetools               4.1.1
certifi                  2020.6.20
chardet                  3.0.4
colorama                 0.4.3
cycler                   0.10.0
DateTime                 4.3
distlib                  0.3.1
execnet                  1.7.1
filelock                 3.0.12
google-api-core          1.22.4
google-api-python-client 1.12.3
google-auth              1.22.1
google-auth-httplib2     0.0.4
google-auth-oauthlib     0.4.1
googleapis-common-protos 1.52.0
httplib2                 0.18.1
idna                     2.10
importlib-metadata       1.6.0
kiwisolver               1.2.0
matplotlib               3.3.2
more-itertools           8.3.0
MouseInfo                0.1.3
numpy                    1.19.2
oauth2client             4.1.3
oauthlib                 3.1.0
packaging                20.4
pbr                      5.4.5
Pillow                   8.0.0
pip                      20.2.3
pluggy                   0.13.1
protobuf                 3.13.0
py                       1.8.1
pyasn1                   0.4.8
pyasn1-modules           0.2.8
PyAutoGUI                0.9.52
PyDrive                  1.3.1
PyGetWindow              0.0.9
PyMsgBox                 1.0.9
pyparsing                2.4.7
pyperclip                1.8.1
PyRect                   0.1.4
PyScreeze                0.1.26
pytest                   5.4.2
pytest-cache             1.0
python-dateutil          2.8.1
PyTweening               1.0.3
pytz                     2020.1
PyYAML                   5.3.1
requests                 2.24.0
requests-oauthlib        1.3.0
rsa                      4.6
setuptools               40.8.0
six                      1.15.0
speedtest-cli            2.1.2
sqlparse                 0.3.1
stevedore                3.0.0
uritemplate              3.0.1
urllib3                  1.25.10
virtualenv               20.0.26
virtualenv-clone         0.5.4
virtualenvwrapper        4.8.4
virtualenvwrapper-win    1.2.6
wcwidth                  0.1.9
words                    0.0.1
zipp                     3.1.0
zope.interface           5.1.2
WARNING: You are using pip version 20.2.3; however, version 20.2.4 is available.
You should consider upgrading via the 'c:\users\rahul\appdata\local\programs\python\python37-32\python.exe -m pip install --upgrade pip' command.

F:\Python\speedtest\internet_monitor-master>

**Comment by jsphwllng** [comment]
can you try pulling the repo again please. does your folder also have csv files saved in them? if so can you share one of the contents?

thanks :)

**Comment by rahulxdd** [comment]
Just tried on a different internet connection. And it showed the same error.


time | downspeed | upspeed |  
-- | -- | -- | --
  |   |   |  
20:50:54 | 7.51 | 1.95 |  
  |   |   |  
20:51:17 | 6.89 | 1.95 |  
  |   |   |  
20:51:39 | 7.36 | 1.95 |  
  |   |   |  
20:52:01 | 7.24 | 1.93 |  
  |   |   |  
20:52:23 | 7.29 | 1.96 |  
  |   |   |  
20:52:45 | 7.81 | 1.8 |

**Comment by jsphwllng** [comment]
This is very odd - what is the name of that csv file?

**Comment by rahulxdd** [comment]
> This is very odd - what is the name of that csv file?

2020-10-26_speed.csv

**Comment by jsphwllng** [comment]
https://github.com/jsphwllng/internet_monitor/commit/293aa007b6a5b3c1a6a0d66cba77e5f974954814

I have changed how the CSV file is being read - please pull and try again.

**Comment by rahulxdd** [comment]
> [293aa00](https://github.com/jsphwllng/internet_monitor/commit/293aa007b6a5b3c1a6a0d66cba77e5f974954814)
> 
> I have changed how the CSV file is being read - please pull and try again.

Working perfectly. I think we can close the issue now.
