### ISSUE TITLE
excuse me I am getting this error while importing speedtest. Can you help me?

### ISSUE THREAD

**Issue by RamazanKurnaz** [jsphwllng/internet_monitor#2]
![www](https://user-images.githubusercontent.com/40741837/97765651-f8fbf800-1b23-11eb-880f-54916702654e.JPG)

**Comment by RamazanKurnaz** [comment]
just ım try to speedtest download
Im dowload pip install speedtest but this.... ı not know

**Comment by jsphwllng** [comment]
Which version of python are you using, did you follow the readme?

**Comment by RamazanKurnaz** [comment]
ım using 3.8.3 Yes ı m read :(

**Comment by jsphwllng** [comment]
it's called speed-test-cli and not speedtest. please use the requirements.txt to install instead of manually.
